# Experimental Bluetooth settings that improve wireless connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Increase Bluetooth TX power for better range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Workaround for bug in Windows battery notifications
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n